name: Milk-V Duo - Build Image

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board to target'
        type: choice
        default: 'duos-wifi'
        options:
        - 'duos'
        - 'duos-wifi'
        - 'duo256m'
      compile:
        description: 'Compile from source'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.compile }}

      - name: Build in container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:noble
          options: --privileged -v ${{ github.workspace }}:/project -w /project
          run: |
            apt-get update -y
            apt-get install -y git
            git clone https://github.com/pengutronix/genimage.git
            ./scripts/setup.sh
            [ "${{ inputs.compile }}" = "true" ] && ./scripts/compile.sh
            ./build.sh ${{ inputs.board }}

      - name: Upload Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: milkv-${{ inputs.board }}-img-${{ github.run_id }}
          path: images/ubuntu-noble-milkv-${{ inputs.board }}.img
